### 
POST http://localhost/api/random1/random2
Content-Type: application/json

{
    "Name" : "john",
    "Age" : 3
}

###
GET http://localhost/api/name=John&&Age=2
Host: hoster
User-Agent: agent

###
GET http://localhost/api/file/hello.txt

{
    "Hello" : "hi"
}
###
GET http://localhost/api/fiadsle/dasdload?=

###
GET http://localhost/api/user/show/Hellos
Content-Type: application/json

###
GET http://localhost/api/user/index

###
GET http://localhost/api/user/create
Content-Type: application/json

###
POST http://localhost/api/user/create
Authorization: 3b14e5eab0a2a471abbc035594c8127f
Content-Type: multipart/form-data; boundary=---------------------------275960504307967009023195

-----------------------------275960504307967009023195
Content-Disposition: form-data; name="username"

aaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
-----------------------------275960504307967009023195
Content-Disposition: form-data; name="password"

aaaaa
-----------------------------275960504307967009023195--

###
POST http://localhost/api/user/delete/woohoo
Content-Type: multipart/form-data
Authorization: e8662945f14038986e6c93aa71e0a5ed

###
POST http://localhost/api/user/
Content-Type: application/json
Authorization: 589e1c71c4584a210de128ee364694a1

{ 
    "username" : "admin20",
    "password" : "admin01"
}

###
OPTIONS http://localhost/api/user/delete/1

###
POST http://localhost/api/user/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin01"
}

###
POST http://localhost/api/user/logout
Authorization: 5528662d11870068162564dddbe89c45
Content-Type: application/json
