### 
POST http://localhost/api/random1/random2
Content-Type: application/json

{
    "Name" : "john",
    "Age" : 3
}

###
GET http://localhost/api/name=John&&Age=2
Host: hoster
User-Agent: agent

###
GET http://localhost/api/file/hello.txt

{
    "Hello" : "hi"
}
###
GET http://localhost/api/fiadsle/dasdload?=
Content-Type: application/json

###
GET http://localhost/api/user/shows/
Content-Type: application/json

###
GET http://localhost/api/user/
Content-Type: application/json

###
GET http://localhost/api
Content-Type: application/json

###
GET http://localhost/api/user/create/
Content-Type: application/json

###
GET http://localhost/api/test
Content-Type: application/json

###
GET http://localhost/api/users/
Content-Type: application/json

###
POST http://localhost/api/user/create
Authorization: 323058c35ebdc99cf989f7cda255d54b
Content-Type: multipart/form-data; boundary=---------------------------275960504307967009023195

-----------------------------275960504307967009023195
Content-Disposition: form-data; name="username"

aaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
-----------------------------275960504307967009023195
Content-Disposition: form-data; name="password"

aaaaa
-----------------------------275960504307967009023195--

###
POST http://localhost/api/user/delete/woohoo
Content-Type: multipart/form-data;
Authorization: f248197069e7bb92e4f10fdc2910f9f5

###
POST http://localhost/api/user/
Content-Type: application/json
Authorization: b4a7cd0cda315c2d30ae4ff0c2a48cbc

{ 
    "username" : "adm05",
    "password" : "adm1"
}

###
OPTIONS http://localhost/api/user/delete/1
Content-Type: s

###
GET http://localhost/api/res/1
Content-Type: application/json


###
POST http://localhost/api/user/login/
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin01"
}

###
POST http://localhost/api/user/logout
Authorization: 60ec228deb4a51f695ea08831fe956b5
Content-Type: application/json
