### 
POST http://localhost/api/random1/random2
Content-Type: application/json

{
    "Name" : "john",
    "Age" : 3
}

###
GET http://localhost/api/name=John&&Age=2
Host: hoster
User-Agent: agent

###
GET http://localhost/api/file/hello.txt

{
    "Hello" : "hi"
}
###
GET http://localhost/api/fiadsle/dasdload?=

###
GET http://localhost/api/user/show

###
GET http://localhost/api/user/index/

###
POST http://localhost/api/user/create
Content-Type: multipart/form-data; boundary=---------------------------275960504307967009023195

-----------------------------275960504307967009023195
Content-Disposition: form-data; name="username"

aaa
-----------------------------275960504307967009023195
Content-Disposition: form-data; name="password"

aaaaa
-----------------------------275960504307967009023195--

###
POST http://localhost/api/user/delete/1

###
POST http://localhost/api/user/
Content-Type: application/json

{ 
    "username" : "aaa",
    "password" : "Pasaaaaaas"
}

###
OPTIONS http://localhost/api/user/delete/1